#!/usr/bin/env bash
# Transfers file from our client to given server
# arg 1 path of file to copy
# arg 2 ip of server
# arg 3 username to use
# arg 4 path to ssh key to use
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 3 ]
then
	scp -o StrictHostKeyChecking=no $1 $3@$2:
else
	scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:
fi
